name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Tests
      run: pytest tests/test_api.py

  docker_build_and_deploy:
    runs-on: ubuntu-latest
    needs: build_and_test

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

    - name: Build Docker Image
      run: docker build -t your-docker-username/your-docker-image-name .

    - name: Push Docker Image to Docker Hub
      run: docker push your-docker-username/your-docker-image-name

    - name: Deploy to Cloud (AWS ECS)
      run: |
        aws ecs update-service \
          --cluster your-cluster \
          --service your-service \
          --force-new-deployment
