name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    # Step 3: Install dependencies
    - name: Install Dependencies
      run: pip install -r requirements.txt

    # Step 4: Run Tests
    - name: Run Tests
      run: pytest

    # Step 5: Build Docker Image
    - name: Build Docker Image
      run: docker build -t my-app:${{ github.sha }} .

    # Step 6: Push to Docker Hub (requires secrets)
    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Push Docker Image
      run: docker push my-app:${{ github.sha }}

    # Step 7: Deploy to AWS ECS (requires AWS credentials)
    - name: Deploy to AWS ECS
      uses: aws-actions/amazon-ecs-deploy-task-definition@v1
      with:
        task-definition: ecs-task-def.json
        service: my-ecs-service
        cluster: my-cluster
        wait-for-service-stability: true
